/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nfq_internship_task;

/**
 *
 * @author Rengetsu
 */
public class DisplayBoard extends javax.swing.JFrame {

    /**
     * Creates new form DisplayBoard
     */
    public DisplayBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenPanel = new javax.swing.JPanel();
        taskIcon = new javax.swing.JLabel();
        closeDisplayBoardButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        screenTable = new javax.swing.JTable();
        refreshInfoText = new javax.swing.JLabel();
        lineLabel = new javax.swing.JLabel();
        pageNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        screenPanel.setBackground(new java.awt.Color(255, 255, 255));

        taskIcon.setFont(new java.awt.Font("Lato Black", 0, 28)); // NOI18N
        taskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logo.png"))); // NOI18N
        taskIcon.setText("NFQ INTERNSHIP TASK");

        closeDisplayBoardButton.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        closeDisplayBoardButton.setText("Close Department Screen");
        closeDisplayBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDisplayBoardButtonActionPerformed(evt);
            }
        });

        screenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0001", "1", "2021-04-06 10:00:00", "Dr. Kabajashi Bashi", "Mark", "Registered"},
                {"0002", "1", "2021-04-06 11:00:00", "Dr. Kabajashi Bashi", "Agne", "Registered"},
                {"0003", "2", "2021-04-06 12:00:00", "Kakashi Hatake", "Alex", "Registered"},
                {"0004", "1", "2021-04-06 13:00:00", "Dr. Kabajashi Bashi", "Vika", "Registered"},
                {"0005", "2", "2021-04-06 14:00:00", "Kakashi Hatake", "Sasha", "Registered"}
            },
            new String [] {
                "Visi number", "Specialist number", "Visit date & time", "Specialist name", "Customer name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(screenTable);

        refreshInfoText.setFont(new java.awt.Font("Lato Black", 0, 11)); // NOI18N
        refreshInfoText.setText("The service department screen automatically refreshes every 5 seconds");

        lineLabel.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        lineLabel.setText("_____________________________________________");

        pageNameLabel.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        pageNameLabel.setText("Service Department Screen");

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screenPanelLayout.createSequentialGroup()
                        .addComponent(scrollPane)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                        .addGap(0, 176, Short.MAX_VALUE)
                        .addGroup(screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                                .addComponent(taskIcon)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                                .addComponent(pageNameLabel)
                                .addGap(243, 243, 243))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                                .addComponent(lineLabel)
                                .addGap(208, 208, 208))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeDisplayBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshInfoText))
                .addGap(149, 149, 149))
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshInfoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeDisplayBoardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeDisplayBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDisplayBoardButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeDisplayBoardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeDisplayBoardButton;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JLabel pageNameLabel;
    private javax.swing.JLabel refreshInfoText;
    private javax.swing.JPanel screenPanel;
    private javax.swing.JTable screenTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel taskIcon;
    // End of variables declaration//GEN-END:variables
}
